# .github/workflows/ci.yml

# Continuous Integration (CI) Workflow
name: ci

# This workflow will run whenever we push commits to the `main` branch, or
# whenever there's a pull request to the `main` branch. See:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#on
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' # Choose the Python version you need for your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black
        # If you have a requirements.txt file, uncomment the following line:
        # pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 .

    - name: Format with black
      run: |
        # Check if the code format is in compliance with black
        black . --check
